arco-design/arco-plugins

packages/plugin-webpack-react/src/arco-design-plugin/plugin-for-theme.js, packages/plugin-webpack-react/src/arco-design-plugin/utils/transform-import.js, packages/utils/src/index.js
| Component | Changelog(CN) | Changelog(EN) | Related issues | 
| --------- | ------------- | ------------- | -------------- |
=> fix: import less by path

packages/plugin-webpack-react/src/arco-design-plugin/plugin-for-theme.js
=> fix(webpack-react): does not support chain syntax

packages/plugin-vite-react/src/arco-design-plugin/config.ts, packages/plugin-vite-react/src/arco-design-plugin/icon.ts
- [- ] Bug fix
新版本web-react ，使用iconBox会报错
=> fix：修正新版本 web-react 使用 iconbox 会报错的问题

packages/plugin-vite-react/src/arco-design-plugin/icon.ts
- [-] Performance improvement
Pre-bundling
=> feat：Improve icons' loading speed

README.md, packages/plugin-vite-react/src/arco-design-plugin/config.ts, packages/plugin-vite-react/src/arco-design-plugin/icon.ts, packages/plugin-vite-react/src/arco-design-plugin/transform.ts, packages/plugin-vite-vue/.gitignore, packages/plugin-vite-vue/README.md, packages/plugin-vite-vue/README.zh-CN.md, packages/plugin-vite-vue/package.json, packages/plugin-vite-vue/src/arco-design-plugin/config.ts, packages/plugin-vite-vue/src/arco-design-plugin/icon.ts, packages/plugin-vite-vue/src/arco-design-plugin/index.ts, packages/plugin-vite-vue/src/arco-design-plugin/less.ts, packages/plugin-vite-vue/src/arco-design-plugin/transform.ts, packages/plugin-vite-vue/src/arco-design-plugin/typings.d.ts, packages/plugin-vite-vue/src/arco-design-plugin/utils.ts, packages/plugin-vite-vue/src/index.ts, packages/plugin-vite-vue/tsconfig.json, yarn.lock
- [-] New feature
Vite plugin for vue
=> feat：vite插件的vue版本

packages/plugin-vite-react/README.md, packages/plugin-vite-react/README.zh-CN.md, packages/plugin-vite-react/src/arco-design-plugin/config.ts, packages/plugin-vite-react/src/arco-design-plugin/icon.ts, packages/plugin-vite-react/src/arco-design-plugin/index.ts, packages/plugin-vite-react/src/arco-design-plugin/less.ts, packages/plugin-vite-react/src/arco-design-plugin/utils.ts, packages/plugin-vite-vue/README.md, packages/plugin-vite-vue/README.zh-CN.md, packages/plugin-vite-vue/src/arco-design-plugin/config.ts, packages/plugin-vite-vue/src/arco-design-plugin/icon.ts, packages/plugin-vite-vue/src/arco-design-plugin/index.ts, packages/plugin-vite-vue/src/arco-design-plugin/less.ts, packages/plugin-vite-vue/src/arco-design-plugin/utils.ts
- [ -] New feature
之前是全局注入，可能会引起一些问题，增加配置可按需注入
=> feat：支持主题样式变量注入配置

packages/plugin-vite-react/src/index.ts, packages/plugin-vite-vue/src/index.ts
=> feat：导出 vitePluginForArco 变量

packages/plugin-vite-react/README.md, packages/plugin-vite-react/src/arco-design-plugin/index.ts, packages/plugin-vite-react/src/arco-design-plugin/less.ts, packages/plugin-vite-react/src/arco-design-plugin/utils.ts, packages/plugin-vite-vue/README.md, packages/plugin-vite-vue/src/arco-design-plugin/index.ts, packages/plugin-vite-vue/src/arco-design-plugin/less.ts, packages/plugin-vite-vue/src/arco-design-plugin/utils.ts
varsInjectScope 参数支持正则表达式，例如 ['src',/node_modules\/package\//]
正则表达式不可以有 flags，也就是包含 i,g 等flag，必须以 / 开头和结尾
=> feat：varsInjectScope 参数支持正则表达式，例如 ['src',/node_modules\/package\//]

packages/plugin-vite-vue/src/arco-design-plugin/utils.ts
| 支持组件大驼峰写法 | support component writing by pascal-case | |
由于 volar 对组件 props 提示不友好，需要改为大驼峰写法才能以支持，如：`<AButton>` 、`<AInput>` ...，所以需要插件支持这种写法，配合 unplugin-vue-components 插件完整支持模板方式的按需导入。
=> feat: support component writing by pascal-case

packages/plugin-vite-vue/src/arco-design-plugin/transform.ts
| 支持 `<script lang="jsx">` | support `<script lang="jsx">` | |
=> feat(plugin-vite-vue): support <script lang="jsx">

packages/plugin-vite-vue/src/arco-design-plugin/transform.ts
| 支持 vite 3.x | support vite 3.x | |
=> feat(plugin-vite-vue): support vite 3.x

packages/plugin-webpack-react/README.md, packages/plugin-webpack-react/README.zh-CN.md, packages/plugin-webpack-react/src/arco-design-plugin/interface.ts, packages/plugin-webpack-react/src/arco-design-plugin/loaders/transform-import.ts, packages/plugin-webpack-react/src/arco-design-plugin/plugin-for-import.ts, packages/plugin-webpack-react/src/arco-design-plugin/utils/transform-import.ts, packages/plugin-webpack-react/tsconfig.json
=> fix(plugin-webpack-react): add babel filename & support inject babel-plugin-import for babel-loader

packages/plugin-webpack-react/src/arco-design-plugin/index.ts
=> Compatible with `(new ArcoWebpackPlugin()).pluginForImport.getBabelPlugins()` usage

packages/plugin-vite-react/package.json, packages/plugin-vite-react/src/arco-design-plugin/transform.ts, packages/plugin-vite-react/src/arco-design-plugin/utils.ts, packages/plugin-vite-vue/package.json, packages/plugin-vite-vue/src/arco-design-plugin/utils.ts
新版本的 vue 组件库，会导出一些 hooks，引入这些hook时，会导致错误发生
增加样式文件判断
=> fix：解决从新版本组件库引入 hooks 之类的非组件会报错的问题

packages/plugin-vite-vue/src/arco-design-plugin/transform.ts, packages/plugin-vite-vue/src/arco-design-plugin/utils.ts
| 支持在模板中自动导入 | Support auto import in template | Close #32  |
| 支持所有组件导入 | Support import of all components | Close #32  |
| 优化组件样式导入逻辑 | Optimize component style import logic | Close #32  |
=> feat(plugin-vite-vue): Support auto import in template

packages/plugin-vite-vue/README.md, packages/plugin-vite-vue/README.zh-CN.md, packages/plugin-vite-vue/src/arco-design-plugin/icon.ts, packages/plugin-vite-vue/src/arco-design-plugin/index.ts, packages/plugin-vite-vue/src/arco-design-plugin/transform.ts, packages/plugin-vite-vue/src/arco-design-plugin/utils.ts
存在问题 https://github.com/arco-design/arco-plugins/pull/34#issuecomment-1275510335
读取 [@arco-design/web-vue/es/index.d.ts](https://github.com/arco-design/arco-design-vue/blob/main/packages/web-vue/components/index.ts) 文件导出的所有组件
遍历 [@arco-design/web-vue/es](https://github.com/arco-design/arco-design-vue/tree/main/packages/web-vue/components) 目录里非 `_` 开头和非 `style` 的子目录的 `index.d.ts` 文件，读取该文件导出的所有组件
- 大驼峰命名，如：`TimePicker`
- 非类型文件，即：`exportKind === 'value'`
| 支持 `<ATimePicker />` `<A-TimePicker />` `<A-Time-Picker />` 写法 | Support `<ATimePicker />` `<A-TimePicker />` `<A-Time-Picker />` style | #34 |
| 兼容旧版本组件库 | Compatible with legacy component library | #34 |
| 支持图标前缀 | Support icon prefix | …
=> enhance(plugin-vite-vue): Compatible with older versions

packages/plugin-webpack-react/package.json, packages/plugin-webpack-react/src/arco-design-plugin/index.ts, packages/plugin-webpack-react/src/arco-design-plugin/plugin-for-import.ts
某些场景下，include 中的一些文件没有配置 Babel-loader，会导致编译错误。例如，arco组件库被引用在第三方组件库中，而第三方组件库可能默认没有babel-loader。
判断babel-loader是否已经配置了
=> fix:error occurs without babel-loader

packages/plugin-webpack-react/src/arco-design-plugin/utils/transform-import.ts
当 option 中设置了 preset 时，如果 preset 和 插件中默认的 preset 重复，构建会失败。
例如，期望更改插件中默认使用的  `@babel/preset-react` 的配置，会出现此问题：
```
babelConfig: {
presets: [
[
'@babel/preset-react',
{
runtime: 'automatic', 
},
],
],
}
```
当检测存在重复 preset 时，合并 preset 的 option，而不是直接追加 preset。
=> fix: merge babel preset

packages/plugin-vite-vue/README.md, packages/plugin-vite-vue/README.zh-CN.md, packages/plugin-vite-vue/src/arco-design-plugin/index.ts
When we copy the icon from the [docs](https://arco.design/vue/component/icong), it comes with a prefix of `icon`. However, our current configuration does not include this prefix by default. Therefore, we need to manually add a configuration in plugins to ensure consistency. 
This commit simplifies the configuration, related issue: https://github.com/arco-design/arco-plugins/issues/45
```ts
export default defineConfig({
plugins: [
vitePluginForArco({
iconPrefix: 'icon',
}),
],
})
```
| iconPrefix增加默认值 `icon` | iconPrefix default value `icon` | https://github.com/arco-design/arco-plugins/issues/45 |
=> feat: default icon prefix

package.json, packages/plugin-webpack-react/package.json, packages/plugin-webpack-react/src/arco-design-plugin/interface.ts, packages/plugin-webpack-react/src/arco-design-plugin/plugin-for-import.ts, packages/plugin-webpack-react/src/arco-design-plugin/utils/transform-import.ts, yarn.lock
`modifyBabelLoader` will override babel plugins in specified modules. This will result in unpredictable compilation outcomes.
It is expected not to cause any issues, but it may lead to unexpected behavior in cases where the original dependencies relied on this bug. Please help test the functionality of related modules.
=> fix: `modifyBabelLoader` will override babel plugins in specified modules

packages/plugin-webpack-react/src/arco-design-plugin/utils/transform-import.ts
=> fix: `modifyBabelLoaderMerge` failed to merge config

packages/plugin-webpack-react/src/arco-design-plugin/plugin-for-theme.ts
因为插件内部处理机制，导致token固化的缘故。
当前插件无法彻底把css变量前缀改得很彻底。
虽然 有 `@arco-cssvars-prefix: if(@arco-vars-prefix = ~'', -, ~'--@{arco-vars-prefix}')` 这种语句。
但是token在处理前值已经固化了。如果要想实现css变量的变更。使用时要配置如下才能生效
modifyVars: {
prefix: 've-o',
'arco-vars-prefix': 've-o',
'arco-cssvars-prefix': '--ve-o', // 此处要显性添加
},
<br class="Apple-interchange-newline">
=> fix(plugin-webpack-react): 修复css变量失效问题

packages/plugin-webpack-react/src/arco-design-plugin/plugin-for-theme.ts
=> fix(plugin-webpack-react): 补充判断逻辑

packages/unplugin-react/src/plugins/theme.ts
=> fix(unplugin): fix rspack problem

packages/unplugin-react/src/plugins/remove-font-face.ts, packages/unplugin-react/src/plugins/replace-default-language.ts
=> fix(unplugin): fix undefined problem

packages/unplugin-react/src/plugins/theme.ts, packages/unplugin-react/src/utils/theme.ts
=> fix: modify less vars

packages/unplugin-react/src/plugins/theme.ts
=> feat(unplugin): support custom cssvars prefix

packages/unplugin-react/package.json, packages/unplugin-react/src/loaders/append.ts
The CSS declarations in tokens.less are created repeatedly, resulting in numerous CSS variables and causing Chrome DevTools to lag.
=> perf: remove duplicate css vars in dev
